runtime: nodejs22
instance_class: F1 

readiness_check:
  path: "/health-check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

automatic_scaling:
  min_instances: 0 
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75